### ISSUE TITLE
Unable to download files 

### ISSUE THREAD

**Issue by Demorde** [VoxelBoy/MobileUO#1]
I am trying to get this to work on a Samsung S10E using the UO Rennisance package. I have the files hosted on Linux using Python3's HTTP server. I can visit the local IP address in the browser and it connects. There is no visit attempt by the client in the server logs.

I copied the server information exactly as shown on the Wiki.

**Comment by VoxelBoy** [comment]
I should have mentioned somewhere that the client assumes the web server runs on port 8080. Looks like Python3's HTTP server defaults to 8000. Can you give it another try by changing the port?

**Comment by Demorde** [comment]
That fixed it, setting 8080 allowed it to download the files.

May I suggest specifying where we could manually place the files on the device instead of having to download them from a local server?

**Comment by VoxelBoy** [comment]
Yes, several people are asking for this so I'll work on an update tonight that allows this.
