### ISSUE TITLE
WebGl

### ISSUE THREAD

**Issue by MBoberski** [VoxelBoy/MobileUO#5]
Can it be compiled to WebGl client?

**Comment by VoxelBoy** [comment]
Check out this fork: https://github.com/MythikGN/MobileUO/tree/webgl-support

**Comment by MBoberski** [comment]
Shit... there is no issue there, I can't ask for tutorial how to run it or even it it will be udpated. Maybe you know any answer for my questions?

**Comment by VoxelBoy** [comment]
Join the MobileUO discord so I can help you a bit better: https://discord.gg/d6NQsj3
